title: Joseph Verron - Caring Coder
email: joseph@verron.pro
description: >-
  "Caring Coder" is a blog dedicated to software professionals with insights and techniques to excel in agile development, and to discuss about automating process, reducing technical debt, assessing and developing team's skills, and creating productivity tools.

baseurl: "/blog"
url: "https://verron.pro"

github_username: caring-coder

repository: verronpro/blog

lang: en
timezone: Asia/Shanghai

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
